[icons]
icons = "awesome6"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"


[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = " $icon $available.eng(w:4) "
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "custom"
interval = 600
command = "sh -c 'p=$(pacman -Qu --dbpath /tmp/checkup-db-i3statusrs-$USER 2>/dev/null | wc -l); a=$(yay -Qua 2>/dev/null | wc -l); echo \"pacman $p yay $a\"'"
format = " $text"


[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wired} $speed_up.eng(prefix:K) $speed_down.eng(prefix:K) "
interval = 5


[[block]]
block = "memory"
format = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "memory"
format = " $icon U:$mem_used.eng(w:2) A:$mem_avail.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "qpwgraph"

[[block]]
block = "time"
interval = 1
[block.format]
full = " $icon $timestamp.datetime(f:'%Y-%m-%d %H:%M:%S(%a)') "
