#!/bin/bash

selection=$(rofi -lines 12 -padding 15 -width 55 -theme solarized -dmenu $@ < $HOME/.local/share/snippets/bookmarks)
kaomoji=$(echo $selection)
echo -n "$kaomoji" | cut -d' ' -f1 | xclip -selection clipboard
sleep 0.1
xsel -b