#!/bin/bash

selection=$(rofi -i -width 1000 -theme solarized -dmenu $@ < $HOME/.local/share/snippets/bookmarks)
kaomoji=$(echo $selection)
echo -n "$kaomoji" | cut -d' ' -f1 |xclip -selection clipboard
sleep 0.1
xsel -b