#!/bin/bash

selection=$(rofi -lines 12 -padding 15 -width 55 -location 0 -sidebar-mode -columns 3 -font 'Noto Sans 12' -dmenu $@ < $HOME/.local/share/snippets/bookmarks)
kaomoji=$(echo $selection)
echo -n "$kaomoji" | cut -d' ' -f1 | xclip -selection clipboard
sleep 0.1
xsel -b